Task 01
LabutinIgor/spbau-software-design pull request #1
Opened 2016-10-01 12:43 UTC by LabutinIgor

2016-10-16 12:32 UTC, yurii-litvinov requested changes
- при ошибке во вводе всё падает (например, при использовании необъявленной переменной окружения)
- на несуществующие команды консоль никак не реагирует, хотя исправно пишет в лог, что не так
- echo '123$x'
  123 $x
  --- лишних пробелов подставляться не должно, и при сильном, и при слабом квотировании
- диаграмма из-за обилия перекрещивающихся стрелочек не очень читаема
  В целом мне нравится, написано аккуратно, но замечания всё-таки поправьте, пожалуйста.

2016-10-16 12:32 UTC, yurii-litvinov commented on src/main/java/ru/spbau/mit/Environment.java
> +    This method assigns value to variable
В JavaDoc по традиции строчки начинают с "*", как у Вас в комментарии к классу.

2016-10-16 12:32 UTC, yurii-litvinov commented on src/test/java/ru/spbau/mit/ParserTest.java
> +            fail("Unexpected exception: ", exception);
Зачем? Сама тестовая система ведь поймает исключение и выдаст диагностику, в тестах вообще очень редко пишут try/catch.

2016-11-02 14:43 UTC, LabutinIgor commented
Исправил

2016-11-05 20:54 UTC, yurii-litvinov approved these changes

2016-11-05 20:54 UTC, yurii-litvinov commented on src/main/java/ru/spbau/mit/Lexer.java
> + * words and service symbols and then substituting variables
Не совсем по-английски. Лучше "contains methods for division of line into words" или что-то вроде.

2016-11-05 20:54 UTC, merged